FROM alpine

# 安装 libpcap 库，因为静态编译的二进制文件可能仍然需要它
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add tzdata
# 设置工作目录
WORKDIR /app

# 复制配置文件和证书
COPY main-linux-amd64 /app/main
COPY settings.yaml /app

# 启动应用程序
CMD ["./main"]

# docker build -t sunset:v1 .