monitor: # 监控配置
  cityList: # 监控的城市，支持多个城市的监听
    - 长沙
    - 广州
  evening: # 晚霞的监控配置，当前获取当天的晚霞
    enable: true # 是否启用
    quality: 0.2 # 校验指标，满足指标就进行推送
    time: 0 24 11,13,16 * * * # 定时任务的时间配置
  morning: # 朝霞的监控配置，当天获取第二天的朝霞
    enable: false
    quality: 0.7
    time: 0 0 19,20 * * *
  map: # 地图配置
    enable: true # 获取火烧云的图
    region: "中东" # 默认是中东部  覆盖中国大部分城市

bot:
  enable: false
  targetList: # 推送的目标，支持多个
    - name: ft # 推送的目标：ft：方糖，也就是server酱
      sendKey: "" # server酱上面的sendKey
    - name: ft
      sendKey: ""